version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 120
      runas: root
